name: Mobile Automation CI

on:
  workflow_dispatch:
  push:
    # branches:
    #   - main
  pull_request:
    branches:
      - main

env:
  ANDROID_AVD: emulator

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout do código
        uses:  actions/checkout@v4

      # - name: Install Java 21
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: 'zulu'
      #     java-version: '21'

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Env vars
        run: |
          export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
          echo $ANDROID_HOME
          adb devices
          ANDROID_HOME/emulator/emulator -list-avds
      
      - name: Appium Install
        run: |
          npm install -g appium
          # appium setup
          appium driver install uiautomator2

      - name: Appium Doctor
        run: |
          appium driver doctor uiautomator2

      - name: Robot Framework Install
        run: pip install robotframework robotframework-appiumlibrary

      
          
      # - name: 🚀 Iniciar Appium Server
      #   run: appium --log-level error > appium.log 2>&1 &

      # - name: 🎯 Executar testes com Robot Framework
      #   run: |
      #     robot --outputdir results tests/

      # - name: 📤 Upload dos logs e relatórios
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-results
      #     path: results/
