name: Mobile Automation CI

on:
  workflow_dispatch:
  push:
    # branches:
    #   - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout do código
        uses:  actions/checkout@v4

      - name: Install Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Appium Install
        run: |
          npm install -g appium
          appium setup
          # appium driver install uiautomator2

      - name: Appium Doctor
        run: |
          appium driver doctor uiautomator2

      - name: Robot Framework Install
        run: pip install robotframework robotframework-appiumlibrary

      
          
      # - name: 🚀 Iniciar Appium Server
      #   run: appium --log-level error > appium.log 2>&1 &

      # - name: 🎯 Executar testes com Robot Framework
      #   run: |
      #     robot --outputdir results tests/

      # - name: 📤 Upload dos logs e relatórios
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-results
      #     path: results/
